---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### Class Notes for 2021-05-12

Fork/clone our repo: https://github.com/davidkane9/RFC

Today's data comes from the National Institute of Justice’s (NIJ) [Recidivism Forecasting Challenge](https://nij.ojp.gov/funding/recidivism-forecasting-challenge). "The Challenge uses data on roughly 26,000 individuals from the State of Georgia released from Georgia prisons on discretionary parole to the custody of the Georgia Department of Community Supervision (GDCS) for the purpose of post-incarceration supervision between January 1, 2013 and December 31, 2015."

[Code book](https://nij.ojp.gov/funding/recidivism-forecasting-challenge-appendix-2-codebook.pdf) for the data.

Background readings:

* Barabas C, Dinakar K, Doyle C. (2019) "[The Problems With Risk Assessment Tools](https://www.nytimes.com/2019/07/17/opinion/pretrial-ai.html)." The New York Times.

* Dastin J (2018) "[Amazon scraps secret AI recruiting tool that showed bias against
women](https://www.reuters.com/article/us-amazon-com-jobsautomation-
insight-idUSKCN1MK08G)."  Reuters.

Other links:

* Good issue of R Weekly from [Monday](https://rweekly.org/#RWeekly2021-W19map-walk-pivot,centrelperk,ShinyDevSeries).

* Please pass along to your high school friends: [Kane’s Free High School Data Science Bootcamp](https://bootcamp.davidkane.info/).
